### ISSUE TITLE
Support multiple Azure CLI version on each release

### ISSUE THREAD

**Issue by bgauduch** [Zenika/terraform-azure-cli#84]
In order to provide a fallback option if breaking changes or bugs occurs between 2 Azure CLI version, an option could be to support both the latest and n-1 versions in each release.

Using the Github Actions matrix strategy in the release job:
```yaml
strategy:
      matrix:
        tf_version:
          - "0.11.14"
          - "0.12.28"
          - "0.13.0-beta3"
        azcli_version:
          - "2.7.0"
          - "2.8.0"
```
